packages:
  - "apps/*"
  - "packages/*"

overrides:
  ioredis: "5.6.1"

allowBuilds:
  bufferutil: true
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
